name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Tests
        run: |
          echo "Running Tests"
          pytest